services:
  - type: web
    name: policy-qa-app
    env: python
    plan: starter # good for small projects; upgrade if needed
    pythonVersion: 3.10 # ensures compatibility with pinecone & dependencies
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: BEARER_TOKEN
        sync: false
      - key: GEMINI_EMBD_KEY
        sync: false
    instanceCount: 1
    instanceType: starter
    # healthCheckPath: /health
